local Addon, Core = _G.YiboReputation, _G.YiboCore
local Theme = Core.UITheme
local function Text(parent,size,color,justify) return Theme:CreateText(parent,size,color,justify or "LEFT") end
local function Snapshot(c) return Core.DataDomains:Get(c.id,"reputation") end
local function Data(c,id) return Addon:GetFactionData(Snapshot(c), id) end
local function CharacterName(character)
 return (character and character.name and character.name ~= "" and character.name)
  or (character and Core.Characters:GetDisplayName(character, "short"))
  or "未知角色"
end
local function CharacterColor(character)
 local color = character and RAID_CLASS_COLORS and RAID_CLASS_COLORS[character.class or ""]
 return color or Theme.Colors.text
end
function Addon:CreateMonitoredPreview(parent)
 parent.monitoredRows={};parent.monitoredDetail=Text(parent,Theme.Font.assist,Theme.Colors.muted,"LEFT");parent.monitoredHeaders={}
 parent.monitoredPrev=Theme:CreateButton(parent,26,"<","secondary");parent.monitoredNext=Theme:CreateButton(parent,26,">","secondary")
end
function Addon:RefreshMonitoredPreview(parent,context)
 local ids=self:GetSettings().monitoredFactionIDs;parent.monitoredDetail:Hide()
 if #ids==0 then parent.monitoredPrev:Hide();parent.monitoredNext:Hide();for _,r in ipairs(parent.monitoredRows) do r:Hide() end;for _,header in ipairs(parent.monitoredHeaders) do header:Hide() end;return end
 local inset=Theme:GetMatrixInsets(true);local compact=#context.characters>10;local nameWidth,cellWidth=150,(compact and 56 or 90);local visible=math.max(1,math.floor(((parent:GetWidth() or 420)-nameWidth-inset.left-inset.right)/cellWidth));local pages=math.max(1,math.ceil(#context.characters/visible));local settings=self:GetSettings();settings.monitoredPage=math.max(1,math.min(tonumber(settings.monitoredPage) or 1,pages));local first=(settings.monitoredPage-1)*visible+1;local last=math.min(#context.characters,first+visible-1);local y=inset.top
 local headerY=y;for ci=0,last-first+1 do local character=ci>0 and context.characters[first+ci-1] or nil;local header=parent.monitoredHeaders[ci+1] or Text(parent,Theme.Font.assist,Theme.Colors.muted,ci==0 and "LEFT" or "CENTER");parent.monitoredHeaders[ci+1]=header;header:ClearAllPoints();header:SetPoint("TOPLEFT",parent,"TOPLEFT",inset.left+(ci==0 and 0 or nameWidth+(ci-1)*cellWidth),-headerY);header:SetWidth((ci==0 and nameWidth or cellWidth)-6);header:SetText(ci==0 and "声望" or CharacterName(character));local color=ci==0 and Theme.Colors.muted or CharacterColor(character);header:SetTextColor(color.r or color[1],color.g or color[2],color.b or color[3]);header:Show() end;for ci=last-first+2,#parent.monitoredHeaders do parent.monitoredHeaders[ci]:Hide() end;y=y+Theme.Size.compact
 for index,id in ipairs(ids) do local row=parent.monitoredRows[index] or CreateFrame("Button",nil,parent,"BackdropTemplate");parent.monitoredRows[index]=row;row:SetSize(nameWidth+(last-first+1)*cellWidth,Theme.Table.rowHeight);row:ClearAllPoints();row:SetPoint("TOPLEFT",parent,"TOPLEFT",inset.left,-y);row:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8x8",edgeFile="Interface\\Buttons\\WHITE8x8",edgeSize=1});row:SetBackdropColor((index%2==0 and Theme.Colors.alternate or Theme.Colors.row)[1],(index%2==0 and Theme.Colors.alternate or Theme.Colors.row)[2],(index%2==0 and Theme.Colors.alternate or Theme.Colors.row)[3],1);row:SetBackdropBorderColor(Theme.Colors.matrixLine[1],Theme.Colors.matrixLine[2],Theme.Colors.matrixLine[3],Theme.Colors.matrixLine[4]);row.cells=row.cells or {};row.columnTints=row.columnTints or {};row.columnDividers=row.columnDividers or {};local vals={self:GetFactionName(id)};for ci=first,last do local c=context.characters[ci];local s=Snapshot(c);vals[#vals+1]=self:FormatSnapshotValue(s,Data(c,id),compact and "compact" or "matrix",self:GetFactionState(s,id)) end;local x=0;for ci,v in ipairs(vals) do if ci>1 then local tint=row.columnTints[ci] or row:CreateTexture(nil,"ARTWORK",nil,-2);row.columnTints[ci]=tint;tint:ClearAllPoints();tint:SetPoint("TOPLEFT",row,"TOPLEFT",x,0);tint:SetSize(cellWidth,Theme.Table.rowHeight);local tone=(ci%2==0) and Theme.Colors.current or Theme.Colors.selected;tint:SetColorTexture(tone[1],tone[2],tone[3],0.18);tint:Show();local divider=row.columnDividers[ci] or row:CreateTexture(nil,"OVERLAY");row.columnDividers[ci]=divider;divider:ClearAllPoints();divider:SetPoint("TOPLEFT",row,"TOPLEFT",x,0);divider:SetPoint("BOTTOMLEFT",row,"BOTTOMLEFT",x,0);divider:SetWidth(1);divider:SetColorTexture(Theme.Colors.matrixLine[1],Theme.Colors.matrixLine[2],Theme.Colors.matrixLine[3],Theme.Colors.matrixLine[4]);divider:Show() end;local cell=row.cells[ci] or Text(row,Theme.Font.assist,Theme.Colors.text,"LEFT");row.cells[ci]=cell;cell:ClearAllPoints();cell:SetPoint("LEFT",row,"LEFT",x+4,0);cell:SetWidth((ci==1 and nameWidth or cellWidth)-6);cell:SetText(v);cell:Show();x=x+(ci==1 and nameWidth or cellWidth) end;for ci=#vals+1,#row.cells do row.cells[ci]:Hide() end;for ci=#vals+1,#row.columnTints do row.columnTints[ci]:Hide() end;for ci=#vals+1,#row.columnDividers do row.columnDividers[ci]:Hide() end;row:Show();y=y+Theme.Table.rowHeight end
 for i=#ids+1,#parent.monitoredRows do parent.monitoredRows[i]:Hide() end
 parent.monitoredNext:ClearAllPoints();parent.monitoredNext:SetPoint("TOPRIGHT",parent,"TOPRIGHT",-inset.right,-headerY);parent.monitoredPrev:ClearAllPoints();parent.monitoredPrev:SetPoint("RIGHT",parent.monitoredNext,"LEFT",4,0);parent.monitoredPrev:SetShown(pages>1);parent.monitoredNext:SetShown(pages>1);parent.monitoredPrev:SetState(settings.monitoredPage>1 and "default" or "disabled");parent.monitoredNext:SetState(settings.monitoredPage<pages and "default" or "disabled");parent.monitoredPrev:SetScript("OnClick",function() if settings.monitoredPage>1 then settings.monitoredPage=settings.monitoredPage-1;self:NotifyChanged() end end);parent.monitoredNext:SetScript("OnClick",function() if settings.monitoredPage<pages then settings.monitoredPage=settings.monitoredPage+1;self:NotifyChanged() end end)
end
